export 'package:practica_final_2/models/movie.dart';
export 'package:practica_final_2/models/now_playing_response.dart';
export 'dart:convert';
export 'popular_response.dart';
export 'cast.dart';
export 'search_response.dart';
export 'top_rated_response.dart';
export 'upcoming_response.dart';
export 'similar_response.dart';